### PR TITLE
Switch to use a new relay chain module

### PR DESCRIPTION
**Pull request by bluele**

### CODE REVIEW

**Comment by bluele** [comment]
@toshihiko-okubo could you review this?

**Review by dongrie — APPROVED** [review]
[LGTM](https://lgtm.lol/i/756)

**Comment by bluele** [comment]
@dongrie sorry, the previous commit has conflict with the latest v0.3. I've rebased with the latest one, so can you review this again?

**Review by dongrie — APPROVED** [review]
LGTM

**Pull request merged**
